services:
  trainer-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 7xTr1YrLRmKOxwTb
    volumes:
      - ./db_mysql:/var/lib/mysql
  trainer-redis:
    image: redis
  trainer-laravel:
    image: trainer-php
    build: .
    environment:
      DB_CONNECTION: mysql
      DB_HOST: trainer-mysql
      DB_DATABASE: snxx_trainer
      DB_USERNAME: root
      DB_PASSWORD: 7xTr1YrLRmKOxwTb
      REDIS_HOST: trainer-redis
    volumes:
      - ./laravel:/var/www/html
    links:
      - trainer-mysql
      - trainer-redis
  trainer-nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - trainer-laravel